FROM nginx:alpine
COPY index.html /usr/share/nginx/html/index.html
COPY users.html /usr/share/nginx/html/users.html
COPY about.html /usr/share/nginx/html/about.html
COPY nginx.conf /etc/nginx/nginx.conf