apiVersion: v1
kind: Pod
metadata:
  name: frontend
  namespace: html-app
  labels:
    app: html-app
spec:
  containers:
  - name: frontend-web
    image: manojt5/project-frontend:latest
    ports:
    - containerPort: 80